Update setup script

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,6 +1,20 @@
 #!/usr/bin/env bash
+#
+# Dotfiles setup script
+# Author: Conor Martin
 
-dotfiles="bash_profile bashrc dircolors gvimrc vimrc"
+# Secure the script, this breaks $* but you should probably be using $@ anyway
+IFS='
+  '
+
+# Set PATH to sane defaults
+PATH=/usr/local/bin:/usr/bin:/bin
+export PATH
+
+# Global variables
+EXITCODE=0
+PROG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+DOTFILES="bash_profile bashrc dircolors gvimrc vimrc"
 
 append_once() {
   # Usage: append_once "string" "file"
@@ -13,19 +27,47 @@ append_once() {
     echo "$string" | sudo tee -a "$file"
   fi
 }
-echo_title() {
-  tput setaf 3 # Yellow text
-  printf "\n\n$1\n\n"
-  tput sgr0 # Reset to default
+
+check(){
+  # Usage: check $? "Task description"
+  if [[ ${1} -eq 0 ]]; then
+    okay "${2} complete"
+  else
+    fail "${2} failed"
+  fi
 }
+
+fail(){
+  printf "[ "; tput setaf 1; printf "FAIL"; tput sgr0; printf " ] "
+  tput setaf 8; printf "%s\n\n" "${1}"; tput sgr0
+  exit 1
+}
+
+info(){
+  printf "\n[ "; tput setaf 6; printf "INFO"; tput sgr0; printf " ] "
+  tput setaf 8; printf "%s\n" "${1}"; tput sgr0
+}
+
+okay(){
+  printf "[ "; tput setaf 2; printf "OKAY"; tput sgr0; printf " ] "
+  tput setaf 8; printf "%s\n\n" "${1}"; tput sgr0
+}
+
+warn(){
+  printf "[ "; tput setaf 3; printf "WARN"; tput sgr0; printf " ] "
+  tput setaf 8; printf "%s\n\n" "${1}"; tput sgr0
+  EXITCODE=$((EXITCODE + 1))
+}
+
 setup_git() {
+  # Skip if running as root
   if [[ $EUID -ne 0 ]]; then
-    echo_title "Git Configuration"
+    info "Git configuration"
     if [ "$interactive" -eq 0 ];then
-      read -rp "Enter Git Name: " gitName
+      read -rp "Enter Git name: " gitName
       if ! [ -z "$gitName" ]; then
         git config --global user.name "$gitName"
-        read -rp "Enter Git Email: " gitEmail
+        read -rp "Enter Git email: " gitEmail
         if ! [ -z "$gitEmail" ]; then
           git config --global user.email "$gitEmail"
           if ! [ -f ~/.ssh/id_rsa ]; then
@@ -33,71 +75,90 @@ setup_git() {
           fi
         fi
       fi
-    fi
-    git config --global color.ui auto
-    git config --global core.editor "$(which vim)"
-    git config --global core.autocrlf input
-    git config --global push.default current
-    git config --global alias.unstage 'reset HEAD --'
-    git config --global alias.last 'log -1 HEAD'
-    git config --global alias.co checkout
-    git config --global alias.br branch
-    git config --global alias.ci commit
-    git config --global alias.s status
+    fi &&
+    git config --global color.ui auto &&
+    git config --global core.editor "$(which vim)" &&
+    git config --global core.autocrlf input &&
+    git config --global push.default current &&
+    git config --global alias.unstage 'reset HEAD --' &&
+    git config --global alias.last 'log -1 HEAD' &&
+    git config --global alias.co checkout &&
+    git config --global alias.br branch &&
+    git config --global alias.ci commit &&
+    git config --global alias.s status &&
     git config --global alias.logp 'log --pretty=oneline --graph'
+    check $? "Git configuration"
   fi
 }
+
 setup_linux() {
-  echo_title "Linking dotfiles"
-  for item in ${dotfiles}; do
-    if [ "${script_dir}/${item}" -ef "${HOME}/.${item}" ]; then
+  info "Linking DOTFILES"
+  for item in ${DOTFILES}; do
+    if [ "${PROG_DIR}/${item}" -ef "${HOME}/.${item}" ]; then
       echo "Skipping ${item}"
     else
-      rm "${HOME}/.${item}"
-      ln -s "${script_dir}/${item}" "${HOME}/.${item}"
       echo "Linking ${item}"
+      rm "${HOME}/.${item}" &&
+      ln -s "${PROG_DIR}/${item}" "${HOME}/.${item}"
     fi
   done
+  check $? "Dotfile linking"
 
-  if [ ! -d "${HOME}/.config/base16-shell" ]; then
-    echo_title "Installing base16-shell"
+  info "Installing base16-shell"
+  if [ -d "${HOME}/.config/base16-shell" ]; then
+    warn "base16-shell directory already exists"
+  else
     git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
+    check $? "base16-shell installation"
+  fi
+  
+  info "Installing base16-vim"
+  if [ -d ~/.vim/bundle/base16-vim ]; then
+    warn "base16-vim directory already exists"
+  else
+    git clone https://github.com/chriskempson/base16-vim.git ~/.vim/bundle/base16-vim
+    check $? "base16-vim installation"
+  fi
+  
+  info "Installing Vundle"
+  if [ -d ~/.vim/bundle/Vundle.vim ]; then
+    warn "Vundle bundle already exists"
+  else
+    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
+    check $? "Vundle installation"
   fi
 
-  if ! [ -d ~/.vim/bundle/base16-vim ]; then
-    echo_title "Installing base16-vim"
-    git clone https://github.com/chriskempson/base16-vim.git ~/.vim/bundle/base16-vim
-  fi
-  if ! [ -d ~/.vim/bundle/Vundle.vim ]; then
-    echo_title "Installing Vundle"
-    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
-  fi
+  info "Installing Vim plugins"
   vim +PluginInstall +qall
+  check $? "Vim plugin installation"
 }
+
 setup_macos() {
   # Skip MacOS configuration if root
   if [ ! "$(id -u)" -eq 0 ]; then
     sudo -v
-    printf "\n"
+    info "Setting Hostname"
     read -rp "Enter Hostname: " name
     if [ ! -z "$name" ]; then
-      echo_title "Setting Hostname"
-      sudo scutil --set ComputerName "$name"
-      sudo scutil --set HostName "$name"
-      sudo scutil --set LocalHostName "$name"
+      sudo scutil --set ComputerName "$name" &&
+      sudo scutil --set HostName "$name" &&
+      sudo scutil --set LocalHostName "$name" &&
       sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$name"
+      check $? "Hostname setup"
+    else
+      warn "Hostname unchanged"
     fi
-
+    
+    info "Installing Homebrew"
     if ! (which brew > /dev/null 2>&1); then
-      echo_title "Installing Homebrew"
       ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
     else
-      echo_title "Updating Homebrew"
-      brew update;
-      brew upgrade;
+      brew update &&
+      brew upgrade
     fi
+    check $? "Homebrew installation"
 
-    echo_title "Install GNU Bash"
+    info "Installing GNU Bash"
     # Add the GNU shell to the list of allowed shells
     if ([ "$( grep -f '/etc/shells' '/usr/local/bin/bash' )" -ge 1 ]) > /dev/null 2>&1; then
       sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'
@@ -105,22 +166,11 @@ setup_macos() {
     # Change to the GNU shell
     # shellcheck disable=SC2024
     sudo chsh -s /usr/local/bin/bash "$USER"
+    check $? "GNU Bash installation"
   fi
 }
 
 clear
-echo_title "Dotfiles Setup Script"
-
-# Get script directory
-source="${BASH_SOURCE[0]}"
-# resolve $source until the file is no longer a symlink
-while [ -h "$source" ]; do
-  script_dir="$( cd -P "$( dirname "$source" )" && pwd )"
-  source="$(readlink "$source")"
-  # if $source was a relative symlink, resolve it
-  [[ $source != /* ]] && source="$script_dir/$source"
-done
-script_dir="$( cd -P "$( dirname "$source" )" && pwd )"
 
 # Check if running from an interactive shell
 if [ -t 0 ]; then
@@ -130,14 +180,12 @@ else
 fi
 
 if ([ "$( uname -s )" = "Darwin" ]) > /dev/null 2>&1; then
-  echo "OS: MacOS"
   setup_macos
   setup_linux
   setup_git
 else
-  echo "OS: Linux"
   setup_linux
   setup_git
 fi
 
-printf "\n\nSetup Complete\n\n"
+exit "${EXITCODE}"
